BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Categories] ADD [IconURL] NVARCHAR(500);

-- AlterTable
ALTER TABLE [dbo].[Users] ADD [Bio] NVARCHAR(500),
[IsEmailVerified] BIT NOT NULL CONSTRAINT [Users_IsEmailVerified_df] DEFAULT 0,
[IsPhoneVerified] BIT NOT NULL CONSTRAINT [Users_IsPhoneVerified_df] DEFAULT 0;

-- AddForeignKey
ALTER TABLE [dbo].[Posts] ADD CONSTRAINT [Posts_Tier_fkey] FOREIGN KEY ([Tier]) REFERENCES [dbo].[PricingTiers]([TierID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
